name: Handle versions of both Client and Server Webhook Job

on:
  repository_dispatch:
    types:
      - versions

jobs:
  client_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.VERSIONS_TOKEN }}
      CLIENT_VERSION: ${{ github.event.client_payload.CLIENT_VERSION }}
    steps:
      - run: gh variable set CLIENT_VERSION --body "$CLIENT_VERSION" --org vuevideo --visibility all

  server_version:
    needs: client_version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.VERSIONS_TOKEN }}
      SERVER_VERSION: ${{ github.event.client_payload.SERVER_VERSION }}
    steps:
      - run: gh variable set SERVER_VERSION --body "$SERVER_VERSION" --org vuevideo --visibility all

