name: Handle versions of both Client and Server Manual Job

on:
  workflow_dispatch:
    inputs:
      CLIENT_VERSION:
        required: true
        type: string
      SERVER_VERSION:
        required: true
        type: string
  repository_dispatch:
    types:
      - versions

jobs:
  client_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.VERSIONS_TOKEN }}
      CLIENT_VERSION: ${{ inputs.CLIENT_VERSION }}
    steps:
      - run: gh variable set CLIENT_VERSION --body "$CLIENT_VERSION" --org vuevideo --visibility all

  server_version:
    needs: client_version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.VERSIONS_TOKEN }}
      SERVER_VERSION: ${{ inputs.SERVER_VERSION }}
    steps:
      - run: gh variable set SERVER_VERSION --body "$SERVER_VERSION" --org vuevideo --visibility all

